# Generated by Django 4.1.2 on 2023-03-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiobooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Not Set', max_length=100)),
                ('last_name', models.CharField(default='Not Set', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='Not Set', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('facebook_id', models.CharField(default='Not Set', max_length=150)),
                ('instagram_id', models.CharField(default='Not Set', max_length=150)),
                ('twitter_id', models.CharField(default='Not Set', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/narrator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NarratedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booksNarated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audiobooks.audiobooks')),
                ('narrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='narrator.narrator')),
            ],
        ),
    ]
