# Generated by Django 4.1.2 on 2023-03-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioBook', models.CharField(blank=True, max_length=50, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
            ],
        ),
    ]
